// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zochpmbukyynxvcjaeyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvY2hwbWJ1a3l5bnh2Y2phZXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTY4OTgsImV4cCI6MjA2NTg3Mjg5OH0.F5Zm_1dX6-3tt9yU_TIW9q-r187BfW89yPeVCjvXyL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);